### PR TITLE
Delete all and delete endpoint

### PR DESCRIPTION
**Pull request by privt00**
yeah added the delete instance and purge all endpoint

/instances/:id/delete
/instances/purge/all

### CODE REVIEW

**Comment by blueiicey** [comment]
💀

**Comment by blueiicey** [comment]
@everyone ???

**Comment by blueiicey** [comment]
@here someone tell me if this works in chat pls

**Comment by blueiicey** [comment]
it doesn't nvm

**Comment by privt00** [comment]
You pinged so many innocent Github users:

**Pull request merged**
